name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev

    - name: Build
      run: |
        make clean
        make

    - name: Test encryption
      run: |
        mkdir -p test
        echo "test content" > test/test.txt
        ./bin/eclipselock -e test/test.txt -k "testkey123"
        ./bin/eclipselock -d test/test.txt.enc -k "testkey123"
        diff test/test.txt <(echo "test content")

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: eclipselock
        path: bin/eclipselock