name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev
    
    - name: Build project
      run: |
        make clean
        make
    
    - name: Create Debian package structure
      run: |
        mkdir -p eclipselock/usr/local/bin
        mkdir -p eclipselock/DEBIAN
        
        # Create control file
        cat > eclipselock/DEBIAN/control << EOF
        Package: eclipselock
        Version: ${GITHUB_REF#refs/tags/v}
        Section: utils
        Priority: optional
        Architecture: amd64
        Depends: libc6 (>= 2.14), libssl3 | libssl1.1
        Maintainer: Jan Fidra <tkmxqrd@gmail.com>
        Description: AES File Encryption Tool
         eclipselock is a command-line tool for encrypting and
         decrypting files using AES-256-CBC encryption.
        EOF
        
        # Create postinst script
        cat > eclipselock/DEBIAN/postinst << EOF
        #!/bin/bash
        chmod 755 /usr/local/bin/eclipselock
        EOF
        
        # Copy binary and set permissions
        cp bin/eclipselock eclipselock/usr/local/bin/
        chmod 755 eclipselock/usr/local/bin/eclipselock
        chmod 755 eclipselock/DEBIAN/postinst
    
    - name: Build Debian package
      run: |
        dpkg-deb --build eclipselock
        mv eclipselock.deb eclipselock_${{ github.ref_name }}_amd64.deb
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          eclipselock_${{ github.ref_name }}_amd64.deb
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}