name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev
    
    - name: Create Custom Makefile
      run: |
        cat > Makefile << EOF
# Custom Makefile for EclipseLock

# Compiler and flags
CXX = g++
CXXFLAGS = -Wall -Wextra -O2 -std=c++14 \$(shell wx-config --cxxflags) \$(shell pkg-config --cflags openssl)
LDFLAGS = \$(shell wx-config --libs) \$(shell pkg-config --libs openssl)

# Source files
SRC = src/main.cpp src/gui/MainWindow.cpp
OBJ = \$(SRC:.cpp=.o)

# Executable name
TARGET = eclipselock

# Default target
all: \$(TARGET)

# Build the executable
\$(TARGET): \$(OBJ)
	\$(CXX) -o \$@ \$^ \$(LDFLAGS)

# Compile source files
%.o: %.cpp
	\$(CXX) \$(CXXFLAGS) -c \$< -o \$@

# Clean up build files
clean:
	rm -f \$(OBJ) \$(TARGET)

# Package the application
package: clean
	mkdir -p EclipseLock/usr/local/bin
	mkdir -p EclipseLock/DEBIAN
	echo "Package: eclipselock" > EclipseLock/DEBIAN/control
	echo "Version: 1.0.0" >> EclipseLock/DEBIAN/control
	echo "Section: utils" >> EclipseLock/DEBIAN/control
	echo "Priority: optional" >> EclipseLock/DEBIAN/control
	echo "Architecture: amd64" >> EclipseLock/DEBIAN/control
	echo "Depends: libc6 (>= 2.14), libssl3 | libssl1.1" >> EclipseLock/DEBIAN/control
	echo "Maintainer: Jan Fidra <tkmxqrd@gmail.com>" >> EclipseLock/DEBIAN/control
	echo "Description: AES File Encryption Tool" >> EclipseLock/DEBIAN/control
	echo " EclipseLock is a command-line tool for encrypting and" >> EclipseLock/DEBIAN/control
	echo " decrypting files using AES-256-CBC encryption." >> EclipseLock/DEBIAN/control
	chmod 644 EclipseLock/DEBIAN/control
	cp \$(TARGET) EclipseLock/usr/local/bin/
	chmod 755 EclipseLock/usr/local/bin/\$(TARGET)
	dpkg-deb --build EclipseLock

.PHONY: all clean package
EOF

    - name: Build project
      run: |
        make clean || echo "Make clean failed, continuing..."
        make package || { echo "Make failed"; exit 1; }
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: eclipselock_1.0.0_amd64.deb
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}