name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libwxgtk3.0-gtk3-dev
    
    - name: Compile Project
      run: |
        g++ -o eclipselock src/main.cpp src/gui/MainWindow.cpp \
        -Wall -Wextra -O2 -std=c++14 `wx-config --cxxflags` `pkg-config --cflags openssl` \
        `wx-config --libs` `pkg-config --libs openssl`
    
    - name: Package the Application
      run: |
        mkdir -p EclipseLock/usr/local/bin
        mkdir -p EclipseLock/DEBIAN
        echo "Package: eclipselock" > EclipseLock/DEBIAN/control
        echo "Version: 1.0.0" >> EclipseLock/DEBIAN/control
        echo "Section: utils" >> EclipseLock/DEBIAN/control
        echo "Priority: optional" >> EclipseLock/DEBIAN/control
        echo "Architecture: amd64" >> EclipseLock/DEBIAN/control
        echo "Depends: libc6 (>= 2.14), libssl3 | libssl1.1" >> EclipseLock/DEBIAN/control
        echo "Maintainer: Jan Fidra <tkmxqrd@gmail.com>" >> EclipseLock/DEBIAN/control
        echo "Description: AES File Encryption Tool" >> EclipseLock/DEBIAN/control
        echo " EclipseLock is a command-line tool for encrypting and" >> EclipseLock/DEBIAN/control
        echo " decrypting files using AES-256-CBC encryption." >> EclipseLock/DEBIAN/control
        chmod 644 EclipseLock/DEBIAN/control
        cp eclipselock EclipseLock/usr/local/bin/
        chmod 755 EclipseLock/usr/local/bin/eclipselock
        dpkg-deb --build EclipseLock
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: eclipselock_1.0.0_amd64.deb
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}