name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev
    
    - name: Build project
      run: |
        make clean
        make
    
    - name: Create Debian package structure
      run: |
        mkdir -p EclipseLock/usr/local/bin
        mkdir -p EclipseLock/DEBIAN
        
        # Create control file
        cat > EclipseLock/DEBIAN/control << EOF
        Package: eclipselock
        Version: ${GITHUB_REF#refs/tags/v}
        Section: utils
        Priority: optional
        Architecture: amd64
        Depends: libc6 (>= 2.14), libssl3 | libssl1.1
        Maintainer: Jan Fidra <tkmxqrd@gmail.com>
        Description: AES File Encryption Tool
         EclipseLock is a command-line tool for encrypting and
         decrypting files using AES-256-CBC encryption.
        EOF
        
        chmod 644 EclipseLock/DEBIAN/control
        
        # Create postinst script
        cat > EclipseLock/DEBIAN/postinst << EOF
        #!/bin/bash
        chmod 755 /usr/local/bin/eclipselock
        EOF
        
        chmod 755 EclipseLock/DEBIAN/postinst
        cp bin/eclipselock EclipseLock/usr/local/bin/
        chmod 755 EclipseLock/usr/local/bin/eclipselock
    
    - name: Build Debian package
      run: |
        dpkg-deb --build EclipseLock
        mv EclipseLock.deb eclipselock_${{ github.ref_name }}_amd64.deb
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: eclipselock_${{ github.ref_name }}_amd64.deb
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}