name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      BUILD_TYPE: Release
      WXWIN: ${{ github.workspace }}/wxWidgets
      OPENSSL_ROOT_DIR: ${{ github.workspace }}/openssl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-wxWidgets3.2
          mingw-w64-x86_64-pkg-config

    - name: Build Project
      shell: msys2 {0}
      run: |
        g++ -o eclipselock src/main.cpp src/gui/MainWindow.cpp src/AESCrypt.cpp \
        -Wall -Wextra -O2 -std=c++14 `wx-config --cxxflags` `pkg-config --cflags openssl` \
        `wx-config --libs` `pkg-config --libs openssl`

    - name: Package Application
      shell: msys2 {0}
      run: |
        mkdir dist
        cp eclipselock dist/
        cp /mingw64/bin/libwx_*.dll dist/
        cp /mingw64/bin/libssl-*.dll dist/
        cp /mingw64/bin/libcrypto-*.dll dist/
        cp /mingw64/bin/libstdc++-*.dll dist/
        cp /mingw64/bin/libgcc_s_*.dll dist/
        cp /mingw64/bin/libwinpthread-*.dll dist/

    - name: Create ZIP archive
      run: |
        Compress-Archive -Path dist/* -DestinationPath eclipselock-windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: EclipseLock-Windows